In [1]:
import numpy as np

In [2]:
a = np.fromstring("1, 2, 3, 3, 1,       6, 8, 11, 10, 7", sep=',').reshape(2, 5).T
a

array([[ 1.,  6.],
       [ 2.,  8.],
       [ 3., 11.],
       [ 3., 10.],
       [ 1.,  7.]])

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
a_centered_sp = np.dot(*a_centered.T)
a_centered_sp

8.0

In [11]:
a_centered_sp / (a.shape[0] - 1)

2.0

In [7]:
np.cov(a.T)[0, 1]

2.0